name: Scoreboard-Info
version: '${project.version}'
main: de.keksgauner.ScoreboardInfo
api-version: 1.18
loadbefore: [ PlotSquared ]
depend: [ PlotSquared, PlaceholderAPI]
authors: [ KeksGauner ]
description: Zeigt in Scoreboard den Plotbesitzer und die Position
website: https://cookieleaks.de
